function Delta = calc_Delta(in1,in2)
%CALC_DELTA
%    DELTA = CALC_DELTA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Dec-2020 21:31:08

J_x = in2(:,1);
J_y = in2(:,2);
J_z = in2(:,3);
m = in2(:,4);
phi = in1(6,:);
psi = in1(4,:);
theta = in1(5,:);
zeta = in1(10,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = 1.0./J_x;
t9 = 1.0./J_y;
t10 = 1.0./m;
t11 = 1.0./t4;
Delta = reshape([-t10.*(t5.*t6+t2.*t3.*t7),t10.*(t3.*t5-t2.*t6.*t7),-t2.*t4.*t10,0.0,0.0,0.0,0.0,(t2.*t11)./J_z,-t3.*t4.*t9.*t10.*zeta,-t4.*t6.*t9.*t10.*zeta,t7.*t9.*t10.*zeta,t5.*t9.*t11,-t8.*t10.*zeta.*(t2.*t6-t3.*t5.*t7),t8.*t10.*zeta.*(t2.*t3+t5.*t6.*t7),t4.*t5.*t8.*t10.*zeta,0.0],[4,4]);
