function T_diffeomorphism = calc_z(in1,in2)
%CALC_Z
%    T_DIFFEOMORPHISM = CALC_Z(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Dec-2020 21:31:08

eta = in1(11,:);
g = in2(:,5);
m = in2(:,4);
p = in1(14,:);
phi = in1(6,:);
psi = in1(4,:);
px = in1(1,:);
py = in1(2,:);
pz = in1(3,:);
q = in1(13,:);
r = in1(12,:);
theta = in1(5,:);
u = in1(7,:);
v = in1(8,:);
w = in1(9,:);
zeta = in1(10,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = 1.0./m;
t9 = t3.*t5;
t10 = t5.*t6;
t11 = t2.*t3.*t7;
t12 = t2.*t6.*t7;
t13 = -t12;
t14 = t10+t11;
t15 = t9+t13;
T_diffeomorphism = [px;t14.*w-v.*(t2.*t6-t7.*t9)+t3.*t4.*u;-t8.*t14.*zeta;-t8.*(eta.*t10+eta.*t11+p.*t2.*t6.*zeta-p.*t7.*t9.*zeta+q.*t3.*t4.*zeta);py;-t15.*w+v.*(t2.*t3+t7.*t10)+t4.*t6.*u;t8.*t15.*zeta;t8.*(eta.*t9+eta.*t13+p.*t2.*t3.*zeta+p.*t7.*t10.*zeta-q.*t4.*t6.*zeta);pz;-t7.*u+t4.*t5.*v+t2.*t4.*w;t8.*(g.*m-t2.*t4.*zeta);t8.*(-eta.*t2.*t4+q.*t7.*zeta+p.*t4.*t5.*zeta);psi;(q.*t5+r.*t2)./t4];
